# Codecov configuration for coverage reporting

coverage:
  precision: 2
  round: down
  range: "85...100"
  
  status:
    project:
      default:
        target: 90%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 85%
        threshold: 5%
        informational: true

# Ignore patterns
ignore:
  - "tests/**/*"
  - "**/__init__.py"
  - "**/test_*.py"
  - "setup.py"
  - "run_tests.py"

# Comment behavior
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# GitHub checks
github_checks:
  annotations: true
